------------------------------------
-------------Chargement des données 
------------------------------------

--CSV
-- customer_demographics

copy into CUSTOMER_DEMOGRAPHICS
from @Amazon_S3/customer_demographics.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

--select * from CUSTOMER_DEMOGRAPHICS


--customer_service_interactions
COPY INTO CUSTOMER_SERVICE_INTERACTIONS
FROM @Amazon_S3/customer_service_interactions.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

--SELECT * FROM CUSTOMER_SERVICE_INTERACTIONS;

--financial_transactions
COPY INTO FINANCIAL_TRANSACTIONS
FROM @Amazon_S3/financial_transactions.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM FINANCIAL_TRANSACTIONS;

--promotions_data
COPY INTO PROMOTIONS_DATA
FROM @Amazon_S3/promotions-data.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM PROMOTIONS_DATA;

--marketing_campaigns
COPY INTO MARKETING_CAMPAIGNS
FROM @Amazon_S3/marketing_campaigns.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM MARKETING_CAMPAIGNS;


--logistics_and_shipping
COPY INTO LOGISTICS_AND_SHIPPING
FROM @Amazon_S3/logistics_and_shipping.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM LOGISTICS_AND_SHIPPING;

--supplier_information
COPY INTO SUPPLIER_INFORMATION
FROM @Amazon_S3/supplier_information.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM SUPPLIER_INFORMATION;

--employee_records
COPY INTO EMPLOYEE_RECORDS
FROM @Amazon_S3/employee_records.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- SELECT * FROM EMPLOYEE_RECORDS;


-- COPY INTO PRODUCT_REVIEWS
-- FROM @Amazon_S3/PRODUCT_REVIEWS.csv
-- FILE_FORMAT = (
--     TYPE = 'CSV'
--     SKIP_HEADER = 1
--     FIELD_OPTIONALLY_ENCLOSED_BY = '"'
-- );


-- SELECT * FROM PRODUCT_REVIEWS;

-- Creation fichier CSV 2

CREATE OR REPLACE FILE FORMAT csv_tab_delimite
  TYPE = 'CSV'
  FIELD_DELIMITER = '\t'  -- TABULATION (pas espace)
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = NONE
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  EMPTY_FIELD_AS_NULL = TRUE;


-- Vider et recharger
TRUNCATE TABLE product_reviews;

COPY INTO product_reviews
FROM @Amazon_S3/product_reviews.csv
FILE_FORMAT = (FORMAT_NAME = 'csv_tab_delimite')
ON_ERROR = 'CONTINUE';

--JSON


COPY INTO JSON_STORE_LOCATIONS_DATA FROM @Amazon_S3/store_locations.json FILE_FORMAT = json;
COPY INTO JSON_INVENTORY_DATA FROM @Amazon_S3/inventory.json FILE_FORMAT = json;

--Vérification du Chargement 


select count (*) from CUSTOMER_SERVICE_INTERACTIONS;
select count (*) from CUSTOMER_DEMOGRAPHICS;
select count (*) from EMPLOYEE_RECORDS;
select count (*) from SUPPLIER_INFORMATION;
select count (*) from MARKETING_CAMPAIGNS;
select count (*) from LOGISTICS_AND_SHIPPING;
select count (*) from PROMOTIONS_DATA;
select count (*) from FINANCIAL_TRANSACTIONS;
select count (*) from  product_reviews;
select count (*) from JSON_INVENTORY_DATA;
select count (*) from JSON_STORE_LOCATIONS_DATA;

-- SELECT  top 10 * from CUSTOMER_SERVICE_INTERACTIONS;
-- SELECT  top 10 * from CUSTOMER_DEMOGRAPHICS;
-- SELECT  top 10 * from EMPLOYEE_RECORDS;
-- SELECT  top 10 * from SUPPLIER_INFORMATION;
-- SELECT  top 10 * from MARKETING_CAMPAIGNS;
-- SELECT  top 10 * from LOGISTICS_AND_SHIPPING;
-- SELECT  top 10 * from PROMOTIONS_DATA;
-- SELECT  top 10 * from FINANCIAL_TRANSACTIONS;
--select top 10 * from    product_reviews;
-- SELECT  top 10 * from JSON_INVENTORY_DATA;
-- SELECT  top 10 * from JSON_STORE_LOCATIONS_DATA;

--Typage

CREATE OR REPLACE TABLE STORE_LOCATIONS AS
SELECT 
   v:"store_id"::VARCHAR AS store_id,
   v:"store_name"::VARCHAR AS store_name,
   v:"store_type"::VARCHAR AS store_type,
   v:"region"::VARCHAR AS region,
   v:"country"::VARCHAR AS country,
   v:"city"::VARCHAR AS city,
   v:"address"::VARCHAR AS address,
   v:"postal_code"::INT AS postal_code,
   v:"square_footage"::DECIMAL(10,2) AS square_footage,
   v:"employee_count"::INT AS employee_count
FROM ANYCOMPANY_LAB.BRONZE.JSON_STORE_LOCATIONS_DATA;

CREATE OR REPLACE TABLE INVENTORY AS
SELECT 
   v:"product_id"::VARCHAR AS product_id,
   v:"product_category"::VARCHAR AS product_category,
   v:"region"::VARCHAR AS region,
   v:"country"::VARCHAR AS country,
   v:"warehouse"::VARCHAR AS warehouse,
   v:"current_stock"::INT AS current_stock,
   v:"reorder_point"::INT AS reorder_point,
   v:"lead_time"::INT AS lead_time,
   v:"last_restock_date"::DATE AS last_restock_date
FROM ANYCOMPANY_LAB.BRONZE.JSON_INVENTORY_DATA;


CREATE OR REPLACE TABLE bronze.FINANCIAL_TRANSACTIONS as
select 
    CAST(TRANSACTION_ID    AS  VARCHAR) as TRANSACTION_ID,
    CAST(TRANSACTION_DATE  AS  DATE) as TRANSACTION_DATE,
    CAST(TRANSACTION_TYPE  AS  VARCHAR) as TRANSACTION_TYPE,
    CAST(AMOUNT            AS  NUMBER(14,2)) as AMOUNT,
    CAST(PAYMENT_METHOD    AS  VARCHAR) as PAYMENT_METHOD,
    CAST(ENTITY            AS  VARCHAR) as ENTITY,
    CAST(REGION            AS  VARCHAR) as REGION,
    CAST(ACCOUNT_CODE       AS VARCHAR) as ACCOUNT_CODE,
    from bronze.FINANCIAL_TRANSACTIONS
;
-- promotions_data
CREATE OR REPLACE TABLE bronze.PROMOTIONS_DATA AS
SELECT 
    CAST(PROMOTION_ID AS VARCHAR) AS PROMOTION_ID,
    CAST(PRODUCT_CATEGORY AS VARCHAR) AS PRODUCT_CATEGORY,
    CAST(PROMOTION_TYPE AS VARCHAR) AS PROMOTION_TYPE,
    CAST(DISCOUNT_PERCENTAGE AS NUMBER(5,2)) AS DISCOUNT_PERCENTAGE,
    CAST(START_DATE AS DATE) AS START_DATE,
    CAST(END_DATE AS DATE) AS END_DATE,
    CAST(REGION AS VARCHAR) AS REGION
FROM bronze.PROMOTIONS_DATA;

-- marketing_campaigns
CREATE OR REPLACE TABLE bronze.MARKETING_CAMPAIGNS AS
SELECT 
    CAST(CAMPAIGN_ID AS VARCHAR) AS CAMPAIGN_ID,
    CAST(CAMPAIGN_NAME AS VARCHAR) AS CAMPAIGN_NAME,
    CAST(CAMPAIGN_TYPE AS VARCHAR) AS CAMPAIGN_TYPE,
    CAST(PRODUCT_CATEGORY AS VARCHAR) AS PRODUCT_CATEGORY,
    CAST(TARGET_AUDIENCE AS VARCHAR) AS TARGET_AUDIENCE,
    CAST(START_DATE AS DATE) AS START_DATE,
    CAST(END_DATE AS DATE) AS END_DATE,
    CAST(REGION AS VARCHAR) AS REGION,
    CAST(BUDGET AS NUMBER(14,2)) AS BUDGET,
    CAST(REACH AS NUMBER(12,0)) AS REACH,
    CAST(CONVERSION_RATE AS NUMBER(5,2)) AS CONVERSION_RATE
FROM bronze.MARKETING_CAMPAIGNS;

-- logistics_and_shipping
CREATE OR REPLACE TABLE bronze.LOGISTICS_AND_SHIPPING AS
SELECT 
    CAST(SHIPMENT_ID AS VARCHAR) AS SHIPMENT_ID,
    CAST(ORDER_ID AS VARCHAR) AS ORDER_ID,
    CAST(SHIP_DATE AS DATE) AS SHIP_DATE,
    CAST(ESTIMATED_DELIVERY AS DATE) AS ESTIMATED_DELIVERY,
    CAST(SHIPPING_METHOD AS VARCHAR) AS SHIPPING_METHOD,
    CAST(STATUS AS VARCHAR) AS STATUS,
    CAST(SHIPPING_COST AS NUMBER(10,2)) AS SHIPPING_COST,
    CAST(DESTINATION_REGION AS VARCHAR) AS DESTINATION_REGION,
    CAST(DESTINATION_COUNTRY AS VARCHAR) AS DESTINATION_COUNTRY,
    CAST(CARRIER AS VARCHAR) AS CARRIER
FROM bronze.LOGISTICS_AND_SHIPPING;

-- supplier_information
CREATE OR REPLACE TABLE bronze.SUPPLIER_INFORMATION AS
SELECT 
    CAST(SUPPLIER_ID AS VARCHAR) AS SUPPLIER_ID,
    CAST(SUPPLIER_NAME AS VARCHAR) AS SUPPLIER_NAME,
    CAST(PRODUCT_CATEGORY AS VARCHAR) AS PRODUCT_CATEGORY,
    CAST(REGION AS VARCHAR) AS REGION,
    CAST(COUNTRY AS VARCHAR) AS COUNTRY,
    CAST(CITY AS VARCHAR) AS CITY,
    CAST(LEAD_TIME AS NUMBER(6,0)) AS LEAD_TIME,
    CAST(RELIABILITY_SCORE AS NUMBER(3,2)) AS RELIABILITY_SCORE,
    CAST(QUALITY_RATING AS VARCHAR(10)) AS QUALITY_RATING
FROM bronze.SUPPLIER_INFORMATION;

-- employee_records
CREATE OR REPLACE TABLE bronze.EMPLOYEE_RECORDS AS
SELECT 
    CAST(EMPLOYEE_ID AS VARCHAR) AS EMPLOYEE_ID,
    CAST(NAME AS VARCHAR) AS NAME,
    CAST(DATE_OF_BIRTH AS DATE) AS DATE_OF_BIRTH,
    CAST(HIRE_DATE AS DATE) AS HIRE_DATE,
    CAST(DEPARTMENT AS VARCHAR) AS DEPARTMENT,
    CAST(JOB_TITLE AS VARCHAR) AS JOB_TITLE,
    CAST(SALARY AS NUMBER(12,2)) AS SALARY,
    CAST(REGION AS VARCHAR) AS REGION,
    CAST(COUNTRY AS VARCHAR) AS COUNTRY,
    CAST(EMAIL AS VARCHAR) AS EMAIL
FROM bronze.EMPLOYEE_RECORDS;

-- customer_demographics
CREATE OR REPLACE TABLE bronze.CUSTOMER_DEMOGRAPHICS AS
SELECT 
    CAST(CUSTOMER_ID AS VARCHAR) AS CUSTOMER_ID,
    CAST(NAME AS VARCHAR) AS NAME,
    CAST(DATE_OF_BIRTH AS DATE) AS DATE_OF_BIRTH,
    CAST(GENDER AS VARCHAR) AS GENDER,
    CAST(REGION AS VARCHAR) AS REGION,
    CAST(COUNTRY AS VARCHAR) AS COUNTRY,
    CAST(CITY AS VARCHAR) AS CITY,
    CAST(MARITAL_STATUS AS VARCHAR) AS MARITAL_STATUS,
    CAST(ANNUAL_INCOME AS NUMBER(12,2)) AS ANNUAL_INCOME
FROM bronze.CUSTOMER_DEMOGRAPHICS;

-- customer_service_interactions
CREATE OR REPLACE TABLE bronze.CUSTOMER_SERVICE_INTERACTIONS AS
SELECT 
    CAST(INTERACTION_ID AS VARCHAR) AS INTERACTION_ID,
    CAST(INTERACTION_DATE AS DATE) AS INTERACTION_DATE,
    CAST(INTERACTION_TYPE AS VARCHAR) AS INTERACTION_TYPE,
    CAST(ISSUE_CATEGORY AS VARCHAR) AS ISSUE_CATEGORY,
    CAST(DESCRIPTION AS VARCHAR) AS DESCRIPTION,
    CAST(DURATION_MINUTES AS NUMBER(6,2)) AS DURATION_MINUTES,
    CAST(RESOLUTION_STATUS AS VARCHAR) AS RESOLUTION_STATUS,
    CAST(FOLLOW_UP_REQUIRED AS BOOLEAN) AS FOLLOW_UP_REQUIRED,
    CAST(CUSTOMER_SATISFACTION AS NUMBER(3,2)) AS CUSTOMER_SATISFACTION
FROM bronze.CUSTOMER_SERVICE_INTERACTIONS;
